In [50]:
from mxnet import nd

In [4]:
x = nd.arange(12)

In [7]:
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [11]:
x[11]


[11.]
<NDArray 1 @cpu(0)>

In [12]:
pip list

Package              Version
-------------------- ---------
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
async-generator      1.10
attrs                21.4.0
backcall             0.2.0
bleach               4.1.0
certifi              2021.5.30
cffi                 1.15.0
chardet              3.0.4
colorama             0.4.4
cycler               0.11.0
d2lzh                1.0.0
dataclasses          0.8
decorator            5.1.1
defusedxml           0.7.1
entrypoints          0.4
graphviz             0.8.4
idna                 2.6
importlib-metadata   4.8.3
ipykernel            5.5.6
ipython              7.16.3
ipython-genutils     0.2.0
ipywidgets           7.7.0
jedi                 0.17.2
Jinja2               3.0.3
jsonschema           4.0.0
jupyter              1.0.0
jupyter-client       7.1.2
jupyter-console      6.4.3
jupyter-core         4.9.2
jupyterlab-pygments  0.1.2
jupyterlab-widgets   1.1.0
kiwisolver           1.3.1
MarkupSafe           2.0.1
matplotlib        

In [21]:
X = nd.arange(12).reshape((3,4))
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Z = Y.zeros_like()
before = id(Z)
Z[:]= X + Y
id(Z) == before

True

In [25]:
from mxnet import nd,autograd

In [35]:
x = nd.arange(4).reshape((4, 1))
x
x.attach_grad()

with autograd.record():
    y = 2 * nd.dot(x.T, x)

y.backward()

In [33]:
assert (x.grad - 4 * x).norm().asscalar() == 0
x.grad
y


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [38]:
assert (x.grad - 4 * x).norm().asscalar() == 0

In [39]:
x.grad - 4 * x


[[0.]
 [0.]
 [0.]
 [0.]]
<NDArray 4x1 @cpu(0)>

In [40]:
nd.random.uniform??

In [41]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [42]:

X = x.reshape((3, 4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [49]:
X.norm()


[22.494442]
<NDArray 1 @cpu(0)>