In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [7]:
Y = net(torch.rand(4, 8))
print(Y.shape)
print(Y.mean())

torch.Size([4, 128])
tensor(1.8626e-09, grad_fn=<MeanBackward0>)


In [8]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [9]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.4254, -0.7977, -1.7686],
        [-0.0274, -2.5947,  0.9318],
        [-1.1957, -1.2526, -0.6300],
        [-0.3836,  1.8486,  1.2645],
        [-0.9681,  1.8493, -0.8270]], requires_grad=True)

In [10]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.8034, 0.0000],
        [0.0000, 0.0000, 0.1525]])

In [11]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[16.0987],
        [21.3076]])

In [12]:
!nvidia-smi

Sun May  8 16:29:45 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 497.47       Driver Version: 497.47       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   40C    P8     3W /  N/A |    106MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [13]:
torch.cuda.device_count()

1